name: Build Datasette website

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events 
  # but only for the master branch
  # and only when this geojson file is pushed
  push:
    paths:
      - 'red-record-states.geojson'
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.5
        
      - name: Run update file
        run: |
          build_script.bat > build_log.txt
        shell: cmd
        
