name: Build Datasette website

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events 
  # but only for the master branch
  # and only when this geojson file is pushed
  push:
    paths:
      - 'red-record-states.geojson'
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.5
        
      - name: Testing Heroku 
        run: |
            echo "installing packages ------------------"
            pip install datasette sqlite-utils heroku
            echo "moving to root -----------------"
            cd ~
            echo "listing files --------------"
            ls -l
            echo "printing to .netrc ------------------"
            sudo (echo "machine api.heroku.com
              login dec11rll@gmail.com
              password 7fae40af-044d-40c4-9955-aea8e7372b63
            machine git.heroku.com
              login dec11rll@gmail.com
              password 7fae40af-044d-40c4-9955-aea8e7372b63") > .netrc
            echo "printing .netrc contents -------------"
            echo "$(.netrc)"
            echo "listing contents -------------"
            ls -l
        shell: bash
        
#      - name: Run set-up file
#        run: |
#          chmod +x ./set-up.sh
#          ./set-up.sh
#        shell: bash

#      - name: Run build file
#        run: |
#          chmod +x ./build_script.sh
#          ./build_script.sh > ./build_log.txt
#        shell: bash
        
      - name: Commit and push build_log.txt
        run: |-
          git config --global user.email build-script-bot@github.com
          git config --global user.name build-script-bot
          git add build_log.txt
          git commit -m "Datasette website updated - see build_log.txt"
          git push
        
